version: '3'

services:
    prometheus:
        image: squeakywheel/prometheus:edge
        ports:
            - 9090:9090
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./config/alerts.yml:/etc/prometheus/alerts.yml

    node-exporter:
        image: prom/node-exporter
        ports:
            - 9100:9100

    telegraf:
        image: squeakywheel/telegraf:edge
        ports:
            - 9273:9273
        volumes:
            - ./config/telegraf.conf:/etc/telegraf/telegraf.conf

    alertmanager:
        image: squeakywheel/prometheus-alertmanager:edge
        ports:
            - 9093:9093
        volumes:
            - ./config/alertmanager.yml:/etc/prometheus/alertmanager.yml

    grafana:
        image: squeakywheel/grafana:edge
        ports:
            - 3000:3000
        volumes:
            - ./config/grafana/provisioning/:/etc/grafana/provisioning/

    cortex:
        image: squeakywheel/cortex:edge
        ports:
            - 9009:9009
        volumes:
            - ./config/cortex.yaml:/etc/cortex/cortex.yaml
        command: [
            "-config.file=/etc/cortex/cortex.yaml"
            ]

    tests:
        image: squeakywheel/lma-integration-tests
        ports:
            - 5001:5001
            - 8080:8080
