apiVersion: 1

datasources:
  - name: prometheus-cortex-lma
    type: prometheus
    access: proxy
    orgId: 1
    url: http://cortex:9009/api/prom
    basicAuth: false
    isDefault: true
    editable: true
